Added typescript type definitions
nearform/get-jwks pull request #108
Opened 2022-01-10 18:54 UTC by ntotten

* Adds `src/get-jwks.d.ts`
* References types from `package.json`

2022-01-10 21:43 UTC, simoneb reviewed
Thanks for this PR! Would you mind adding tests for type definitions using tsd?

2022-01-11 08:25 UTC, radomird requested changes

2022-01-11 08:25 UTC, radomird commented on src/get-jwks.d.ts
> +  catch: LRU<string, JWK>
Shouldn't this be `cache` ?

2022-01-11 08:27 UTC, radomird commented
I agree with Simone, if you could add test that would be great. Thanks.

2022-02-16 13:48 UTC, simoneb commented
@ntotten ping

2022-02-18 18:15 UTC, simoneb commented
@radomird can we pick this up perhaps?

2022-02-22 11:32 UTC, radomird commented
@simoneb & @ntotten 
Since I can't push anything to this branch: https://github.com/zuplo/get-jwks/tree/type_def I've created a fork, added tests there and opened a new PR: https://github.com/nearform/get-jwks/pull/115/ if that one is approved this one can be closed.

2022-02-24 09:57 UTC, radomird commented
Closing this PR as https://github.com/nearform/get-jwks/pull/115 solved the issues mentioned in the comments above.

2022-02-24 09:57 UTC, closed without merging